// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oljanxpqstxvcgkywsyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9samFueHBxc3R4dmNna3l3c3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjE3NzMsImV4cCI6MjA1OTYzNzc3M30.C-IzGLwurGTb7op0oRHKWz4-v4KcLLPIJRZPqjvsTxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);